export { };
const VIDEO_ID = 'ZgWrFoaisdk';
const PIPED_API = `https://api.piped.yt/streams/${VIDEO_ID}`;

async function testPiped() {
    console.log(`\n--- Testing Piped API (api.piped.yt) for ${VIDEO_ID} ---`);
    console.log(`URL: ${PIPED_API}`);
    try {
        const response = await fetch(PIPED_API);
        console.log(`Status: ${response.status}`);

        if (response.status !== 200) {
            console.error(`Piped API returned status ${response.status}`);
            return;
        }

        const data = await response.json();

        if (data.subtitles && data.subtitles.length > 0) {
            console.log(`Found ${data.subtitles.length} subtitle tracks.`);
            console.log("Available tracks:", data.subtitles.map((t: any) => `${t.code} (auto: ${t.autoGenerated})`).join(', '));

            const enTrack = data.subtitles.find((t: any) => t.code === 'en');

            if (enTrack) {
                console.log(`Fetching English track from: ${enTrack.url}`);
                const subResponse = await fetch(enTrack.url);
                const subText = await subResponse.text();
                console.log(`Response Length: ${subText.length}`);
                if (subText.length > 0) {
                    console.log(subText.substring(0, 200));
                } else {
                    console.log("Response is empty.");
                }
            } else {
                console.log("No English track found.");
            }

        } else {
            console.log("No subtitles found in Piped response.");
        }

    } catch (e: any) {
        console.error("Piped failed:", e.message);
    }
}

testPiped();
